FROM ubuntu

ENV BUILD_THREADS=65
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y git

RUN apt-get update && apt-get install -y python3.5 python3-pip build-essential cmake cargo wget
RUN apt-get update && apt install -y python libssl-dev curl pkg-config

RUN wget https://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.bz2
RUN tar xvf binutils-2.27.tar.bz2
RUN cd binutils-2.27 && \
    curl -L 'https://raw.githubusercontent.com/m-labs/conda-recipes/c3effbc26e96c6e246d6e8035f8a07bc52d8ded1/conda/binutils-or1k-linux/fix-R_OR1K_GOTOFF-relocations.patch' | patch -p1 && \
    mkdir build && cd build && \
    ../configure --target=or1k-linux --prefix=/usr/local
RUN cd binutils-2.27/build && make -j${BUILD_THREADS} && make install
